/**
 * Database types generated from Prisma schema
 * This file will be auto-generated by Prisma in the future
 * For now, we define a minimal type for Supabase client
 */

export type Database = {
  public: {
    Tables: {
      profile: {
        Row: {
          id: string;
          external_id: string;
          email: string;
          role: 'ADMIN' | 'ANALYST' | 'VIEWER';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          external_id: string;
          email: string;
          role?: 'ADMIN' | 'ANALYST' | 'VIEWER';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          external_id?: string;
          email?: string;
          role?: 'ADMIN' | 'ANALYST' | 'VIEWER';
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};

